FROM @DOCKER_BASE@
MAINTAINER John Morris <john@zultron.com>

# Tell scripts we're in the container
ENV	IN_DOCKER true

# Install basic build tools and things to help with setup
RUN	apt-get update
RUN	apt-get install -y --no-install-recommends \
	    devscripts \
	    equivs \
	    dpkg-dev \
	    git \
	    subversion \
	    reprepro \
	    ca-certificates \
	    gcc \
	    wget

# Copy scripts and sources
WORKDIR @DOCKER_SRC_DIR@/
ADD	. @DOCKER_SRC_DIR@/

# Install build dependencies and cross-build environment
RUN	./build.sh -i @DEBUG_FLAG@ @CODENAME@ @PACKAGE@
